apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
  name: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  strategy: {}
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - image: gavdraper/microbackweather:v2
          name: microbackweater
