apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather
    layer: front
  name: front-svc
spec:
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: weather
    layer: front
  type: LoadBalancer
